name: Build and Push Multi-Platform Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (para emulación de arm64 en runners amd64)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push para amd64 y arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # Arquitecturas soportadas
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ungoogled-sentinel:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ungoogled-sentinel:${{ github.sha }}
